server:
  port: 80

spring:
  application:
    name: zuul
  thymeleaf:
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka, http://127.0.0.1:8079/eureka
zuul:
  routes:
    user:
      path: /user/**
      serviceId: user
    finance:
      path: /finance/**
      serviceId: finance
