eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
server:
  port: 8769
  
spring:
  application:
    name: service-zuul
    
zuul:
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign