spring: 
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/qq904995993/jk/
          searchPaths: /framework/springcloud/config/config
          username: 
          password: 
      label: master
    
server:
  port: 8084
  
eureka: 
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/, http://localhost:8081/eureka/, http://localhost:8082/eureka/
      
    
 