server:
  port: 8080

spring:
  application:
    name: eureka

eureka:
  instance:
    prefer-ip-address: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    service-url:
      defaultZone: http://127.0.0.1:8079/eureka/



